"use client";

import '/node_modules/primereact/resources/primereact.min.css';
import '/node_modules/primeflex/primeflex.css';
import '/node_modules/primereact/resources/themes/saga-orange/theme.css';
import 'primeicons/primeicons.css';


export const metadata = {
  title: 'BookStore',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='surface-300'>{children}</body>
    </html>
  )
}
