'use client'

import '/node_modules/primereact/resources/primereact.min.css';
import '/node_modules/primeflex/primeflex.css';
import 'primeicons/primeicons.css';
import { ThemeProvider } from 'next-themes'





export const metadata = {
  title: 'Wheather App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">

        <body><ThemeProvider> {children} </ThemeProvider></body>

    </html>
  )
}
