//import './globals.css'
import '/node_modules/primereact/resources/primereact.min.css';
import '/node_modules/primeflex/primeflex.css';
import 'primeicons/primeicons.css';


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link id="theme-link" rel="stylesheet" href="/themes/lara-dark-blue/theme.css"/>
      </head>
      <body>
        {children}
      </body>
    </html>
  )
}
